//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwtbl_queja_alerta
    {
        public long IdRow { get; set; }
        public decimal IdQueja { get; set; }
        public string me_descripcion { get; set; }
        public string de_descripcion { get; set; }
        public string qt_descripcion { get; set; }
        public string qm_descripcion { get; set; }
        public string su_descripcion { get; set; }
        public string qc_descripcion { get; set; }
        public string qe_descripcion { get; set; }
        public string qo_descripcion { get; set; }
        public bool estado { get; set; }
        public System.DateTime qu_fecha { get; set; }
        public Nullable<int> dias_sin_atencion { get; set; }
    }
}
