//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_general : DbContext
    {
        public Entities_general()
            : base("name=Entities_general")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_departamento> tbl_departamento { get; set; }
        public virtual DbSet<tbl_queja_canal> tbl_queja_canal { get; set; }
        public virtual DbSet<tbl_queja_origen> tbl_queja_origen { get; set; }
        public virtual DbSet<tbl_queja_tipo> tbl_queja_tipo { get; set; }
        public virtual DbSet<tbl_queja_tipo_motivo> tbl_queja_tipo_motivo { get; set; }
        public virtual DbSet<tbl_sucursal> tbl_sucursal { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
        public virtual DbSet<tbl_queja_estado> tbl_queja_estado { get; set; }
        public virtual DbSet<tbl_reporte_no_conformidad_det> tbl_reporte_no_conformidad_det { get; set; }
        public virtual DbSet<tbl_reporte_no_conformidad_tipo> tbl_reporte_no_conformidad_tipo { get; set; }
        public virtual DbSet<tbl_reporte_no_conformidad> tbl_reporte_no_conformidad { get; set; }
        public virtual DbSet<tbl_mes> tbl_mes { get; set; }
        public virtual DbSet<tbl_parametros_correo> tbl_parametros_correo { get; set; }
        public virtual DbSet<tbl_queja> tbl_queja { get; set; }
    }
}
