//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reporte_no_conformidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_reporte_no_conformidad()
        {
            this.tbl_reporte_no_conformidad_det = new HashSet<tbl_reporte_no_conformidad_det>();
        }
    
        public decimal IdNoConformidad { get; set; }
        public int IdNoConformidad_tipo { get; set; }
        public decimal IdQueja { get; set; }
        public System.DateTime nc_fecha { get; set; }
        public string nc_descripcion { get; set; }
        public string nc_causa { get; set; }
        public string nc_cumplimiento { get; set; }
        public string nc_verificacion { get; set; }
        public Nullable<System.DateTime> nc_fecha_verificacion { get; set; }
        public string IdUsuario { get; set; }
        public bool estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reporte_no_conformidad_det> tbl_reporte_no_conformidad_det { get; set; }
        public virtual tbl_reporte_no_conformidad_tipo tbl_reporte_no_conformidad_tipo { get; set; }
        public virtual tbl_queja tbl_queja { get; set; }
    }
}
