//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_queja_tipo_motivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_queja_tipo_motivo()
        {
            this.tbl_queja = new HashSet<tbl_queja>();
        }
    
        public int IdQueja_motivo { get; set; }
        public int IdQueja_tipo { get; set; }
        public string qm_descripcion { get; set; }
        public bool estado { get; set; }
    
        public virtual tbl_queja_tipo tbl_queja_tipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_queja> tbl_queja { get; set; }
    }
}
