//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_queja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_queja()
        {
            this.tbl_reporte_no_conformidad = new HashSet<tbl_reporte_no_conformidad>();
        }
    
        public decimal IdQueja { get; set; }
        public int IdQueja_canal { get; set; }
        public int IdQueja_origen { get; set; }
        public int IdSucursal { get; set; }
        public int IdDepartamento { get; set; }
        public int IdQueja_tipo { get; set; }
        public int IdQueja_motivo { get; set; }
        public int IdQueja_estado { get; set; }
        public string qu_detalle { get; set; }
        public string qu_solucion { get; set; }
        public System.DateTime qu_fecha { get; set; }
        public int IdMes { get; set; }
        public int qu_anio { get; set; }
        public string cl_nombre { get; set; }
        public string cl_telefono { get; set; }
        public string cl_correo { get; set; }
        public string IdUsuario { get; set; }
        public bool estado { get; set; }
    
        public virtual tbl_departamento tbl_departamento { get; set; }
        public virtual tbl_mes tbl_mes { get; set; }
        public virtual tbl_queja_canal tbl_queja_canal { get; set; }
        public virtual tbl_queja_estado tbl_queja_estado { get; set; }
        public virtual tbl_queja_origen tbl_queja_origen { get; set; }
        public virtual tbl_queja_tipo tbl_queja_tipo { get; set; }
        public virtual tbl_queja_tipo_motivo tbl_queja_tipo_motivo { get; set; }
        public virtual tbl_sucursal tbl_sucursal { get; set; }
        public virtual tbl_usuario tbl_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_reporte_no_conformidad> tbl_reporte_no_conformidad { get; set; }
    }
}
