//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_parametros_correo
    {
        public int Id { get; set; }
        public string correo_cuenta { get; set; }
        public string correo_cuenta_destinatario { get; set; }
        public string correo_contrasenia { get; set; }
        public string correo_asunto { get; set; }
        public int puerto { get; set; }
        public string host { get; set; }
        public bool permitir_ssl { get; set; }
        public bool enviar_correo_al_guardar_queja { get; set; }
        public string ftp_usuario { get; set; }
        public string ftp_contrasenia { get; set; }
        public string ftp_url { get; set; }
    }
}
