//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_reporte_no_conformidad_det
    {
        public decimal IdNoConformidad { get; set; }
        public int secuencia { get; set; }
        public string nd_actividad { get; set; }
        public int nd_plazo { get; set; }
        public string nd_responsable { get; set; }
    
        public virtual tbl_reporte_no_conformidad tbl_reporte_no_conformidad { get; set; }
    }
}
